package com.zking.pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usertype
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reg_time
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userinfo_id
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    private Integer userinfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usercredit_id
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    private Integer usercreditId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userasset_id
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    private Integer userassetId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usertype
     *
     * @return the value of user.usertype
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usertype
     *
     * @param usertype the value for user.usertype
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reg_time
     *
     * @return the value of user.reg_time
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reg_time
     *
     * @param regTime the value for user.reg_time
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userinfo_id
     *
     * @return the value of user.userinfo_id
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public Integer getUserinfoId() {
        return userinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userinfo_id
     *
     * @param userinfoId the value for user.userinfo_id
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public void setUserinfoId(Integer userinfoId) {
        this.userinfoId = userinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usercredit_id
     *
     * @return the value of user.usercredit_id
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public Integer getUsercreditId() {
        return usercreditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usercredit_id
     *
     * @param usercreditId the value for user.usercredit_id
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public void setUsercreditId(Integer usercreditId) {
        this.usercreditId = usercreditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userasset_id
     *
     * @return the value of user.userasset_id
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public Integer getUserassetId() {
        return userassetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userasset_id
     *
     * @param userassetId the value for user.userasset_id
     *
     * @mbggenerated Sat Jul 15 12:30:56 CST 2017
     */
    public void setUserassetId(Integer userassetId) {
        this.userassetId = userassetId;
    }
}